Example 3/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('home');
});

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/tickets/view/{viewer}', 'TicketController@view');

Route::middleware(['role:'.\App\Models\User::ROLE_SIMPLE_ID.','.\App\Models\User::ROLE_DISPATCHER_ID])->group(function () {
    Route::match(['GET', 'POST'], '/search', 'SearchController@index');
    Route::get('/tickets/checkclients', 'TicketController@checkclients');
    Route::get('/tickets/checkclient', 'TicketController@checkclient');
    Route::get('/tickets/checkplace', 'TicketController@checkPlace');
    Route::get('/tickets/cancel/{id}', 'TicketController@cancel');
    Route::resource('tickets', 'TicketController');
    Route::resource('trips', 'TripController');
    Route::get('/trips/tickets/{trip}', 'TripController@tickets');
    Route::get('/trips/waybill/{trip}', 'TripController@waybill');
    Route::get('/trips/generate/{route}', 'TripController@generate');
    Route::patch('/trips/blockedPlaces/{trip}', 'TripController@updateBlockedPlaces')
        ->name('trips.blockedPlaces.update');

    Route::get('/places/list', 'PlaceController@list');

    Route::get('/clients/list', 'ClientController@list');
    Route::get('/clients/clientsAutocomplite', 'ClientController@clientsAutocomplite');
    Route::resource('clients', 'ClientController');
});

Route::middleware(['role:'.\App\Models\User::ROLE_SIMPLE_ID])->group(function () {
    Route::get('/routes/clone/{route}', 'RouteController@clone');
    Route::get('/routes/pricelist/{route}', 'RouteController@pricelist');
    Route::resource('routes', 'RouteController');
    Route::resource('routeBlockedPlaces', 'RouteBlockedPlaceController');
    Route::resource('routePoints', 'RoutePointController');
    Route::get('points/restore/{id}', 'PointController@restore');
    Route::resource('points', 'PointController');
    Route::get('/routePrices/save', 'RoutePriceController@save');
    Route::get('/routePrices/saveCurrency', 'RoutePriceController@saveCurrency');
    Route::resource('routePrices', 'RoutePriceController');
    Route::resource('schedules', 'ScheduleController', [
        'parameters' => [
            'route' => 'route'
        ]
    ]);

    // Справочники
    Route::resource('agents', 'AgentController');
    Route::resource('langs', 'LangController');
    Route::resource('currencies', 'CurrencyController');
    Route::resource('ticketTypes', 'TicketTypeController', ['trip' => [
        'trip' => 'trip'
    ]]);
    Route::resource('drivers', 'DriverController');
    Route::resource('driverPhones', 'DriverPhoneController', ['parameters' => [
        'driverPhones' => 'driver'
    ]]);
    Route::resource('buses', 'BusController');
    Route::resource('countries', 'CountryController');
    Route::resource('cities', 'CityController');
    Route::resource('places', 'PlaceController');

    // Вспомогательные справочники (без UI)
    Route::resource('schemes', 'SchemeController');

    Route::get('/tripPointBlockeds/block/{trip}/{point}', 'TripPointBlockedController@block');
    Route::resource('tripPointBlockeds', 'TripPointBlockedController');

    Route::resource('dispatcherPhones', 'DispatcherPhoneController');

    Route::resource('settings', 'SettingsController');
    Route::get('/settings/general/{id}/edit', 'SettingsController@editGeneral')
        ->name('settings.general.edit');
    Route::patch('/settings/general/{id}/update', 'SettingsController@updateGeneral')
        ->name('settings.general.update');

    Route::resource('returns', 'ReturnsController');

    Route::resource('users', 'UserController');

    Route::resource('tradingPlatformPoints', 'TradingPlatformPointController', ['only' => [
        'store', 'destroy'
    ]]);
    Route::resource('tradingPlatformTicketVariants', 'TradingPlatformTicketVariantController', ['only' => [
        'store', 'update', 'destroy'
    ]]);
    Route::resource('tradingPlatformRoutes', 'TradingPlatformRoutesController', ['only' => [
        'store', 'destroy'
    ]]);
    Route::resource('tradingPlatforms', 'TradingPlatformController', ['only' => [
        'store', 'update', 'edit', 'destroy', 'create', 'index'
    ]]);
    Route::resource('agentTradingPlatforms', 'AgentTradingPlatformController');
    Route::resource('routeQuotas', 'RouteQuotaController', ['only' => [
        'store'
    ]]);
    Route::resource('tripQuotas', 'TripQuotaController', ['only' => [
        'store'
    ]]);
    Route::resource('activities', 'ActivityController', ['only' => [
        'index'
    ]]);
    Route::resource('reports', 'ReportController', ['only' => [
        'index'
    ]]);
});

Example 3/app/Models/RoutePrice.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class RoutePrice
 * @package App\Models
 * @version July 11, 2018, 2:34 pm UTC
 *
 * @property integer route_id
 * @property integer from_point_id
 * @property integer to_point_id
 * @property integer price
 * @property integer currency_id
 */
class RoutePrice extends Model
{
    use SoftDeletes;

    public $table = 'route_prices';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'route_id',
        'from_point_id',
        'to_point_id',
        'price',
        'currency_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'route_id' => 'integer',
        'from_point_id' => 'integer',
        'to_point_id' => 'integer',
        //'price' => 'integer',
        'currency_id' => 'integer',
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];

    public function route(){
        return $this->belongsTo('App\Models\Route', 'route_id');
    }

    public function from(){
        return $this->belongsTo('App\Models\Point', 'from_point_id');
    }

    public function to(){
        return $this->belongsTo('App\Models\Point', 'to_point_id');
    }

    public function currency(){
        return $this->belongsTo('App\Models\Currency', 'currency_id');
    }


    // Преобразователь прайса
    public function getPriceAttribute($value)
    {
        return $value / 100;
    }

    // Преобразователь прайса
    public function setPriceAttribute($value)
    {
        $this->attributes['price'] = intval($value * 100);
    }

}

Example 3/app/Http/Controllers/RoutePriceController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRoutePriceRequest;
use App\Http\Requests\UpdateRoutePriceRequest;
use App\Models\Currency;
use App\Models\RoutePrice;
use App\Repositories\RoutePriceRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Illuminate\Support\Facades\Validator;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class RoutePriceController extends AppBaseController
{
    /** @var  RoutePriceRepository */
    private $routePriceRepository;

    public function __construct(RoutePriceRepository $routePriceRepo)
    {
        $this->routePriceRepository = $routePriceRepo;
    }

    /**
     * Display a listing of the RoutePrice.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->routePriceRepository->pushCriteria(new RequestCriteria($request));
        $routePrices = $this->routePriceRepository->all();

        return view('route_prices.index')
            ->with('routePrices', $routePrices);
    }

    /**
     * Show the form for creating a new RoutePrice.
     *
     * @return Response
     */
    public function create()
    {
        return view('route_prices.create');
    }

    /**
     * Store a newly created RoutePrice in storage.
     *
     * @param CreateRoutePriceRequest $request
     *
     * @return Response
     */
    public function store(CreateRoutePriceRequest $request)
    {
        $input = $request->all();

        $routePrice = $this->routePriceRepository->create($input);

        Flash::success('Route Price saved successfully.');

        return redirect(route('routes.edit', [$routePrice->route_id]));
    }

    /**
     * Display the specified RoutePrice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $routePrice = $this->routePriceRepository->findWithoutFail($id);

        if (empty($routePrice)) {
            Flash::error('Route Price not found');

            return redirect(route('routePrices.index'));
        }

        return view('route_prices.show')->with('routePrice', $routePrice);
    }

    /**
     * Show the form for editing the specified RoutePrice.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $routePrice = $this->routePriceRepository->findWithoutFail($id);

        if (empty($routePrice)) {
            Flash::error('Route Price not found');

            return redirect(route('routePrices.index'));
        }

        return view('route_prices.edit')->with('routePrice', $routePrice);
    }

    /**
     * Update the specified RoutePrice in storage.
     *
     * @param  int              $id
     * @param UpdateRoutePriceRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRoutePriceRequest $request)
    {
        $routePrice = $this->routePriceRepository->findWithoutFail($id);

        if (empty($routePrice)) {
            Flash::error('Route Price not found');

            return redirect(route('routePrices.index'));
        }

        $routePrice = $this->routePriceRepository->update($request->all(), $id);

        Flash::success('Route Price updated successfully.');

        return redirect(route('routePrices.index'));
    }

    /**
     * Remove the specified RoutePrice from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $routePrice = $this->routePriceRepository->findWithoutFail($id);

        if (empty($routePrice)) {
            Flash::error('Route Price not found');

            return redirect(route('routePrices.index'));
        }

        $this->routePriceRepository->delete($id);

        Flash::success('Route Price deleted successfully.');

        return redirect(route('routePrices.index'));
    }

    public function save(Request $request)
    {
        $input = $request->all();

        $validator = Validator::make($input, [
            'value' => 'required|numeric'
        ]);

        if ($validator->fails()) {
            return json_encode([
                'success'=> false,
                'msg'=> 'Введите цену отрезка'
            ]);
        }

        $params = explode('_', $input['pk']);

        $route_id = $params[0];
        $from_id = $params[1];
        $to_id = $params[2];
        $currency_id = $params[3];

        $routePrice = RoutePrice::where([
            'route_id' => $route_id,
            'from_point_id' => $from_id,
            'to_point_id' => $to_id
        ])->first();

        if(!isset($routePrice)) {
            $routePrice = new RoutePrice();
            $routePrice->route_id = $route_id;
            $routePrice->from_point_id = $from_id;
            $routePrice->to_point_id = $to_id;
        }

        $routePrice->price = $input['value'];
        $routePrice->currency_id = $currency_id;
        if($routePrice->save()){
            return json_encode(['success'=> true]);
        }else{
            return json_encode([
                'success'=> false,
                'msg'=> 'server error'
            ]);
        }
    }

    public function saveCurrency(Request $request)
    {
        $input = $request->all();

        $params = explode('_', $input['pk']);

        $route_id = $params[0];
        $from_id = $params[1];
        $to_id = $params[2];

        $routePrice = RoutePrice::where([
            'route_id' => $route_id,
            'from_point_id' => $from_id,
            'to_point_id' => $to_id
        ])->first();

        if(isset($routePrice)) {
            $routePrice->currency_id = $input['value'];
            if($routePrice->save()){
                return json_encode(['success'=> true]);
            }
        }else{
            return json_encode([
                'success'=> false,
                'msg'=> 'server error'
            ]);
        }
    }
}

Example 3/resources/views/route_prices/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Цена Отрезка</h1>
        <ol class="breadcrumb">
            <li><a href="{!! url('/search') !!}"><i class="fa fa-dashboard"></i>Главная</a></li>
            <li><a href="{!! url('/routePrices') !!}">Цены Отрезков</a></li>
            <li class="active">Создать Цену Отрезка</li>
        </ol>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'routePrices.store']) !!}

                        @include('route_prices.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

Example 3/resources/views/route_prices/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Цена Отрезка</h1>
        <ol class="breadcrumb">
            <li><a href="{!! url('/search') !!}"><i class="fa fa-dashboard"></i>Главная</a></li>
            <li><a href="{!! url('/routePrices') !!}">Цены Отрезков</a></li>
            <li class="active">Редактировать Цену Отрезка</li>
        </ol>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($routePrice, ['route' => ['routePrices.update', $routePrice->id], 'method' => 'patch']) !!}

                        @include('route_prices.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

Example 3/resources/views/route_prices/fields.blade.php
<!-- Route Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('route_id', 'Маршрут:') !!}
    {!! Form::number('route_id', null, ['class' => 'form-control']) !!}
</div>

<!-- From Point Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('from_point_id', 'Из:') !!}
    {!! Form::number('from_point_id', null, ['class' => 'form-control']) !!}
</div>

<!-- To Point Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('to_point_id', 'До:') !!}
    {!! Form::number('to_point_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price', 'Цена:') !!}
    {!! Form::text('price', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('currency_id', 'Валюта:') !!}
    {!! Form::number('currency_id', \App\Models\Currency::getAll(),  null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('routePrices.index') !!}" class="btn btn-default">Отменить</a>
</div>

Example 3/resources/views/route_prices/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Прейскурант Маршрута</h1>
        <ol class="breadcrumb">
            <li><a href="{!! url('/search') !!}"><i class="fa fa-dashboard"></i>Главная</a></li>
            <li class="active">Прейскурант Маршрута</li>
        </ol>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title pull-right">
                    <a class="btn btn-primary pull-right" href="{!! route('routePrices.create') !!}">Добавить</a>
                </h3>
            </div>
            <div class="box-body">
                    @include('route_prices.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

Example 3/resources/views/route_prices/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Цена Отрезка</h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('route_prices.show_fields')
                    <a href="{!! route('routePrices.index') !!}" class="btn btn-default">Назад</a>
                </div>
            </div>
        </div>
    </div>
@endsection

Example 3/resources/views/route_prices/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $routePrice->id !!}</p>
</div>

<!-- Route Id Field -->
<div class="form-group">
    {!! Form::label('route_id', 'Route Id:') !!}
    <p>{!! $routePrice->route_id !!}</p>
</div>

<!-- From Point Id Field -->
<div class="form-group">
    {!! Form::label('from_point_id', 'From Point Id:') !!}
    <p>{!! $routePrice->from_point_id !!}</p>
</div>

<!-- To Point Id Field -->
<div class="form-group">
    {!! Form::label('to_point_id', 'To Point Id:') !!}
    <p>{!! $routePrice->to_point_id !!}</p>
</div>

<!-- Price Field -->
<div class="form-group">
    {!! Form::label('price', 'Price:') !!}
    <p>{!! $routePrice->price !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $routePrice->deleted_at !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $routePrice->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $routePrice->updated_at !!}</p>
</div>

Example 3/resources/views/route_prices/table.blade.php
<table class="table table-responsive" id="routePrices-table">
    <thead>
        <tr>
            <th>Маршрут</th>
            <th>Отрезок от</th>
            <th>до</th>
            <th>Цена</th>
            <th>Валюта</th>
            <th colspan="3">Действия</th>
        </tr>
    </thead>
    <tbody>
    @foreach($routePrices as $routePrice)
        <tr>
            <td>{!! $routePrice->route_id !!}</td>
            <td>{!! $routePrice->from->name !!}</td>
            <td>{!! $routePrice->to->name !!}</td>
            <td>{!! $routePrice->price !!}</td>
            <td>{!! $routePrice->currency->short !!}</td>
            <td>
                {!! Form::open(['route' => ['routePrices.destroy', $routePrice->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <!--<a href="{!! route('routePrices.show', [$routePrice->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>-->
                    <a href="{!! route('routePrices.edit', [$routePrice->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Вы уверены?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>