Example 3/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('home');
});

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/tickets/view/{viewer}', 'TicketController@view');

Route::middleware(['role:'.\App\Models\User::ROLE_SIMPLE_ID.','.\App\Models\User::ROLE_DISPATCHER_ID])->group(function () {
    Route::match(['GET', 'POST'], '/search', 'SearchController@index');
    Route::get('/tickets/checkclients', 'TicketController@checkclients');
    Route::get('/tickets/checkclient', 'TicketController@checkclient');
    Route::get('/tickets/checkplace', 'TicketController@checkPlace');
    Route::get('/tickets/cancel/{id}', 'TicketController@cancel');
    Route::resource('tickets', 'TicketController');
    Route::resource('trips', 'TripController');
    Route::get('/trips/tickets/{trip}', 'TripController@tickets');
    Route::get('/trips/waybill/{trip}', 'TripController@waybill');
    Route::get('/trips/generate/{route}', 'TripController@generate');
    Route::patch('/trips/blockedPlaces/{trip}', 'TripController@updateBlockedPlaces')
        ->name('trips.blockedPlaces.update');

    Route::get('/places/list', 'PlaceController@list');

    Route::get('/clients/list', 'ClientController@list');
    Route::get('/clients/clientsAutocomplite', 'ClientController@clientsAutocomplite');
    Route::resource('clients', 'ClientController');
});

Route::middleware(['role:'.\App\Models\User::ROLE_SIMPLE_ID])->group(function () {
    Route::get('/routes/clone/{route}', 'RouteController@clone');
    Route::get('/routes/pricelist/{route}', 'RouteController@pricelist');
    Route::resource('routes', 'RouteController');
    Route::resource('routeBlockedPlaces', 'RouteBlockedPlaceController');
    Route::resource('routePoints', 'RoutePointController');
    Route::get('points/restore/{id}', 'PointController@restore');
    Route::resource('points', 'PointController');
    Route::get('/routePrices/save', 'RoutePriceController@save');
    Route::get('/routePrices/saveCurrency', 'RoutePriceController@saveCurrency');
    Route::resource('routePrices', 'RoutePriceController');
    Route::resource('schedules', 'ScheduleController', [
        'parameters' => [
            'route' => 'route'
        ]
    ]);

    // Справочники
    Route::resource('agents', 'AgentController');
    Route::resource('langs', 'LangController');
    Route::resource('currencies', 'CurrencyController');
    Route::resource('ticketTypes', 'TicketTypeController', ['trip' => [
        'trip' => 'trip'
    ]]);
    Route::resource('drivers', 'DriverController');
    Route::resource('driverPhones', 'DriverPhoneController', ['parameters' => [
        'driverPhones' => 'driver'
    ]]);
    Route::resource('buses', 'BusController');
    Route::resource('countries', 'CountryController');
    Route::resource('cities', 'CityController');
    Route::resource('places', 'PlaceController');

    // Вспомогательные справочники (без UI)
    Route::resource('schemes', 'SchemeController');

    Route::get('/tripPointBlockeds/block/{trip}/{point}', 'TripPointBlockedController@block');
    Route::resource('tripPointBlockeds', 'TripPointBlockedController');

    Route::resource('dispatcherPhones', 'DispatcherPhoneController');

    Route::resource('settings', 'SettingsController');
    Route::get('/settings/general/{id}/edit', 'SettingsController@editGeneral')
        ->name('settings.general.edit');
    Route::patch('/settings/general/{id}/update', 'SettingsController@updateGeneral')
        ->name('settings.general.update');

    Route::resource('returns', 'ReturnsController');

    Route::resource('users', 'UserController');

    Route::resource('tradingPlatformPoints', 'TradingPlatformPointController', ['only' => [
        'store', 'destroy'
    ]]);
    Route::resource('tradingPlatformTicketVariants', 'TradingPlatformTicketVariantController', ['only' => [
        'store', 'update', 'destroy'
    ]]);
    Route::resource('tradingPlatformRoutes', 'TradingPlatformRoutesController', ['only' => [
        'store', 'destroy'
    ]]);
    Route::resource('tradingPlatforms', 'TradingPlatformController', ['only' => [
        'store', 'update', 'edit', 'destroy', 'create', 'index'
    ]]);
    Route::resource('agentTradingPlatforms', 'AgentTradingPlatformController');
    Route::resource('routeQuotas', 'RouteQuotaController', ['only' => [
        'store'
    ]]);
    Route::resource('tripQuotas', 'TripQuotaController', ['only' => [
        'store'
    ]]);
    Route::resource('activities', 'ActivityController', ['only' => [
        'index'
    ]]);
    Route::resource('reports', 'ReportController', ['only' => [
        'index'
    ]]);
});

Example 3/resources/views/buses/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Автобус</h1>
        <ol class="breadcrumb">
            <li><a href="{!! url('/search') !!}"><i class="fa fa-dashboard"></i>Главная</a></li>
            <li><a href="{!! url('/buses') !!}">Автобусы</a></li>
            <li class="active">Создать автобус</li>
        </ol>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'buses.store']) !!}

                        @include('buses.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

Example 3/resources/views/buses/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Автобус</h1>
        <ol class="breadcrumb">
            <li><a href="{!! url('/search') !!}"><i class="fa fa-dashboard"></i>Главная</a></li>
            <li><a href="{!! url('/buses') !!}">Автобусы</a></li>
            <li class="active">Редактировать Автобус</li>
        </ol>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($bus, ['route' => ['buses.update', $bus->id], 'method' => 'patch']) !!}

                        @include('buses.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

Example 3/resources/views/buses/fields.blade.php
<!-- Sсheme Id Field -->
<div class="form-group col-sm-12">
    {!! Form::label('scheme_id', 'Схема:') !!}
    {!! Form::select('scheme_id', \App\Models\Scheme::getAll(), null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-12">
    {!! Form::label('name', 'Название:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Model Field -->
<div class="form-group col-sm-12">
    {!! Form::label('model', 'Модель:') !!}
    {!! Form::text('model', null, ['class' => 'form-control']) !!}
</div>

<!-- Number Field -->
<div class="form-group col-sm-12">
    {!! Form::label('number', 'Гос Номер:') !!}
    {!! Form::text('number', null, ['class' => 'form-control']) !!}
</div>

<!-- Note Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('note', 'Примечание:') !!}
    {!! Form::textarea('note', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('buses.index') !!}" class="btn btn-default">Отменить</a>
</div>

Example 3/resources/views/buses/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Автобусы</h1>
        <ol class="breadcrumb">
            <li><a href="{!! url('/search') !!}"><i class="fa fa-dashboard"></i>Главная</a></li>
            <li class="active">Автобусы</li>
        </ol>
    </section>
    <section class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title pull-right">
                    <a class="btn btn-primary pull-right" href="{!! route('buses.create') !!}">Добавить</a>
                </h3>
            </div>
            <div class="box-body">
                    @include('buses.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </section>
@endsection

Example 3/resources/views/buses/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Автобус</h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('buses.show_fields')
                    <a href="{!! route('buses.index') !!}" class="btn btn-default">Назад</a>
                </div>
            </div>
        </div>
    </div>
@endsection

Example 3/resources/views/buses/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $bus->id !!}</p>
</div>

<!-- Sсheme Id Field -->
<div class="form-group">
    {!! Form::label('sсheme_id', 'Sсheme Id:') !!}
    <p>{!! $bus->sсheme_id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $bus->name !!}</p>
</div>

<!-- Model Field -->
<div class="form-group">
    {!! Form::label('model', 'Model:') !!}
    <p>{!! $bus->model !!}</p>
</div>

<!-- Number Field -->
<div class="form-group">
    {!! Form::label('number', 'Number:') !!}
    <p>{!! $bus->number !!}</p>
</div>

<!-- Note Field -->
<div class="form-group">
    {!! Form::label('note', 'Note:') !!}
    <p>{!! $bus->note !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $bus->deleted_at !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $bus->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $bus->updated_at !!}</p>
</div>

Example 3/resources/views/buses/table.blade.php
<table class="table table-responsive" id="buses-table">
    <thead>
        <tr>
            <th>Схема</th>
            <th>Название</th>
            <th>Модель</th>
            <th>Гос Номер</th>
            <th>Примечания</th>
            <th colspan="3">Действия</th>
        </tr>
    </thead>
    <tbody>
    @foreach($buses as $bus)
        <tr>
            <td>{!! $bus->scheme->name !!}</td>
            <td>{!! $bus->name !!}</td>
            <td>{!! $bus->model !!}</td>
            <td>{!! $bus->number !!}</td>
            <td>{!! $bus->note !!}</td>
            <td>
                {!! Form::open(['route' => ['buses.destroy', $bus->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <!--<a href="{!! route('buses.show', [$bus->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>-->
                    <a href="{!! route('buses.edit', [$bus->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>