Example 3/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('home');
});

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/tickets/view/{viewer}', 'TicketController@view');

Route::middleware(['role:'.\App\Models\User::ROLE_SIMPLE_ID.','.\App\Models\User::ROLE_DISPATCHER_ID])->group(function () {
    Route::match(['GET', 'POST'], '/search', 'SearchController@index');
    Route::get('/tickets/checkclients', 'TicketController@checkclients');
    Route::get('/tickets/checkclient', 'TicketController@checkclient');
    Route::get('/tickets/checkplace', 'TicketController@checkPlace');
    Route::get('/tickets/cancel/{id}', 'TicketController@cancel');
    Route::resource('tickets', 'TicketController');
    Route::resource('trips', 'TripController');
    Route::get('/trips/tickets/{trip}', 'TripController@tickets');
    Route::get('/trips/waybill/{trip}', 'TripController@waybill');
    Route::get('/trips/generate/{route}', 'TripController@generate');
    Route::patch('/trips/blockedPlaces/{trip}', 'TripController@updateBlockedPlaces')
        ->name('trips.blockedPlaces.update');

    Route::get('/places/list', 'PlaceController@list');

    Route::get('/clients/list', 'ClientController@list');
    Route::get('/clients/clientsAutocomplite', 'ClientController@clientsAutocomplite');
    Route::resource('clients', 'ClientController');
});

Route::middleware(['role:'.\App\Models\User::ROLE_SIMPLE_ID])->group(function () {
    Route::get('/routes/clone/{route}', 'RouteController@clone');
    Route::get('/routes/pricelist/{route}', 'RouteController@pricelist');
    Route::resource('routes', 'RouteController');
    Route::resource('routeBlockedPlaces', 'RouteBlockedPlaceController');
    Route::resource('routePoints', 'RoutePointController');
    Route::get('points/restore/{id}', 'PointController@restore');
    Route::resource('points', 'PointController');
    Route::get('/routePrices/save', 'RoutePriceController@save');
    Route::get('/routePrices/saveCurrency', 'RoutePriceController@saveCurrency');
    Route::resource('routePrices', 'RoutePriceController');
    Route::resource('schedules', 'ScheduleController', [
        'parameters' => [
            'route' => 'route'
        ]
    ]);

    // Справочники
    Route::resource('agents', 'AgentController');
    Route::resource('langs', 'LangController');
    Route::resource('currencies', 'CurrencyController');
    Route::resource('ticketTypes', 'TicketTypeController', ['trip' => [
        'trip' => 'trip'
    ]]);
    Route::resource('drivers', 'DriverController');
    Route::resource('driverPhones', 'DriverPhoneController', ['parameters' => [
        'driverPhones' => 'driver'
    ]]);
    Route::resource('buses', 'BusController');
    Route::resource('countries', 'CountryController');
    Route::resource('cities', 'CityController');
    Route::resource('places', 'PlaceController');

    // Вспомогательные справочники (без UI)
    Route::resource('schemes', 'SchemeController');

    Route::get('/tripPointBlockeds/block/{trip}/{point}', 'TripPointBlockedController@block');
    Route::resource('tripPointBlockeds', 'TripPointBlockedController');

    Route::resource('dispatcherPhones', 'DispatcherPhoneController');

    Route::resource('settings', 'SettingsController');
    Route::get('/settings/general/{id}/edit', 'SettingsController@editGeneral')
        ->name('settings.general.edit');
    Route::patch('/settings/general/{id}/update', 'SettingsController@updateGeneral')
        ->name('settings.general.update');

    Route::resource('returns', 'ReturnsController');

    Route::resource('users', 'UserController');

    Route::resource('tradingPlatformPoints', 'TradingPlatformPointController', ['only' => [
        'store', 'destroy'
    ]]);
    Route::resource('tradingPlatformTicketVariants', 'TradingPlatformTicketVariantController', ['only' => [
        'store', 'update', 'destroy'
    ]]);
    Route::resource('tradingPlatformRoutes', 'TradingPlatformRoutesController', ['only' => [
        'store', 'destroy'
    ]]);
    Route::resource('tradingPlatforms', 'TradingPlatformController', ['only' => [
        'store', 'update', 'edit', 'destroy', 'create', 'index'
    ]]);
    Route::resource('agentTradingPlatforms', 'AgentTradingPlatformController');
    Route::resource('routeQuotas', 'RouteQuotaController', ['only' => [
        'store'
    ]]);
    Route::resource('tripQuotas', 'TripQuotaController', ['only' => [
        'store'
    ]]);
    Route::resource('activities', 'ActivityController', ['only' => [
        'index'
    ]]);
    Route::resource('reports', 'ReportController', ['only' => [
        'index'
    ]]);
});

Example 3/app/Http/Controllers/RouteController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateRouteRequest;
use App\Http\Requests\UpdateRouteRequest;
use App\Models\Currency;
use App\Models\Route;
use App\Repositories\RouteRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class RouteController extends AppBaseController
{
    /** @var  RouteRepository */
    private $routeRepository;

    public function __construct(RouteRepository $routeRepo)
    {
        $this->routeRepository = $routeRepo;
    }

    /**
     * Display a listing of the Route.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->routeRepository->pushCriteria(new RequestCriteria($request));
        $routes = $this->routeRepository->all();

        return view('routes.index')
            ->with('routes', $routes);
    }

    /**
     * Show the form for creating a new Route.
     *
     * @return Response
     */
    public function create()
    {
        return view('routes.create');
    }

    /**
     * Store a newly created Route in storage.
     *
     * @param CreateRouteRequest $request
     *
     * @return Response
     */
    public function store(CreateRouteRequest $request)
    {
        $input = $request->all();

        $route = $this->routeRepository->create($input);

        Flash::success('Route saved successfully.');

        return redirect(route('routes.index'));
    }

    /**
     * Display the specified Route.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $route = $this->routeRepository->findWithoutFail($id);

        if (empty($route)) {
            Flash::error('Route not found');

            return redirect(route('routes.index'));
        }

        return view('routes.show')->with('route', $route);
    }

    /**
     * Show the form for editing the specified Route.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $route = $this->routeRepository->findWithoutFail($id);

        if (empty($route)) {
            Flash::error('Route not found');

            return redirect(route('routes.index'));
        }

        return view('routes.edit')->with('route', $route);
    }

    /**
     * Update the specified Route in storage.
     *
     * @param  int              $id
     * @param UpdateRouteRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateRouteRequest $request)
    {
        $route = $this->routeRepository->findWithoutFail($id);

        if (empty($route)) {
            Flash::error('Route not found');

            return redirect(route('routes.index'));
        }

        $route = $this->routeRepository->update($request->all(), $id);

        Flash::success('Route updated successfully.');

        return redirect(route('routes.index'));
    }

    /**
     * Remove the specified Route from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $route = $this->routeRepository->findWithoutFail($id);

        if (empty($route)) {
            Flash::error('Route not found');

            return redirect(route('routes.index'));
        }

        $route->route_points()->delete();
        $this->routeRepository->delete($id);

        Flash::success('Route deleted successfully.');

        return redirect(route('routes.index'));
    }

    public function clone($route)
    {
        $new_route = Route::cloneRoute($route);

        if (empty($new_route)) {
            Flash::error('Ошибка копирования маршрута');
            return redirect(route('routes.index'));
        }

        Flash::success('Маршрут скопирован удачно.');

        return redirect(route('routes.index'));
    }

    public function pricelist($route)
    {
        $route = $this->routeRepository->findWithoutFail($route);

        if (empty($route)) {
            Flash::error('Route not found');

            return redirect(route('routes.index'));
        }

        $route_prices = [];
        foreach($route->route_prices as $route_price){
            $route_prices[$route_price->from_point_id][$route_price->to_point_id] = [
                'price' => number_format( $route_price->price, 2, '.', ''),
                'currency' => $route_price->currency,
            ];

        }
        return view('routes.pricelist')
            ->with('route', $route)
            ->with('from_points', $route->getAllFromPoints())
            ->with('to_points', $route->getAllToPoints())
            ->with('route_prices', $route_prices)
            ->with('default_currency', Currency::find(1))
            ;
    }
}

Example 3/resources/views/routes/blocked_place_fields.blade.php
<!-- Place Id Field -->
<div class="form-group col-sm-12">
    @include('routes.blocked_place_scheme')
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    <button class="btn btn-primary">Сохранить</button>
</div>

Example 3/resources/views/routes/blocked_place_scheme.blade.php
@section('css')
    <link rel="stylesheet" href="/css/main.css">
@endsection

<div class="bus-scheme-wrap bus-scheme-block-wrap">
    <div class="bus-scheme">
        <div class="driver icon-wrap">
            <img src="/img/driver-icon.png" alt="">
        </div>
        <div class="tv icon-wrap" style="top: 14px;left: 11px;">
            <img src="/img/tv-icon.png" alt="">
            TV
        </div>
        <div class="exit" style="left: 30px;">Exit</div>
        <div class="exit" style="left: 247px;">Exit</div>
        <div class="places-scheme">
            @foreach($route->blockedPlacesInScheme() as $placeInScheme)
                <label class="item" style="left: {{ $placeInScheme['x'] }}px; bottom: {{ $placeInScheme['y'] }}px;">
                    <input
                            type="checkbox"
                            id="{{ $placeInScheme['id'] }}"
                            name="places[]"
                            value="{{ $placeInScheme['id'] }}"
                            @if($placeInScheme['status'] == 1) checked @endif
                    >
                    <span class="index-number">{{ $placeInScheme['num'] }}</span>
                </label>
            @endforeach
        </div>
    </div>
</div>

@section('scripts')
    <script>

    </script>
@endsection

Example 3/resources/views/routes/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Маршрут</h1>
        <ol class="breadcrumb">
            <li><a href="{!! url('/search') !!}"><i class="fa fa-dashboard"></i>Главная</a></li>
            <li><a href="{!! url('/routes') !!}">Маршруты</a></li>
            <li class="active">Создать Маршрут</li>
        </ol>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'routes.store']) !!}

                        @include('routes.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

Example 3/resources/views/routes/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Маршрут</h1>
        <ol class="breadcrumb">
            <li><a href="{!! url('/search') !!}"><i class="fa fa-dashboard"></i>Главная</a></li>
            <li><a href="{!! url('/routes') !!}">Маршруты</a></li>
            <li class="active">Редактировать Маршрут</li>
        </ol>
    </section>
    <section class="content">
        @include('flash::message')
        @include('adminlte-templates::common.errors')
        <div class="row">
            <div class="col-md-12">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Информация о Маршруте</h3>
                    </div>
                    <div class="box-body">
                        <div class="row">
                            {!! Form::model($route, ['route' => ['routes.update', $route->id], 'method' => 'patch']) !!}

                            @include('routes.fields')

                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Отрезки маршрута</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        @if(isset($route->schedule))
                            @include('routes.route_points')
                        @else
                            <div class="callout callout-danger">
                                <h4>Не указано расписание!</h4>
                                <p>Чтобы добавлять отрезки маршрута, нужно указать <a
                                            href="{!! route('schedules.create', ['route' => $route->id]) !!}">расписание</a>
                                </p>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Блокированные места</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body">
                        {!! Form::model($route, ['route' => ['routeBlockedPlaces.update', $route->id], 'method' => 'patch']) !!}

                        @include('routes.blocked_place_fields')

                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Квоты</h3>
                        <div class="box-tools pull-right">
                            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="box-body no-padding">
                        @include('routes.quotas')
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

Example 3/resources/views/routes/fields.blade.php
    <!-- Name Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('name', 'Название:') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}

        @foreach(\App\Models\Lang::all() as $lang_item)
            <div class="form-group col-sm-12">
                <label>Перевод для {{ $lang_item->name }}</label>
                {!! Form::text('translate['.$lang_item->id.']', isset($route) ? $route->getTranslate($lang_item->id) : '', ['class' => 'form-control']) !!}
            </div>
        @endforeach
    </div>

    <!-- Sсheme Id Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('scheme_id', 'Схема мест:') !!}
        {!! Form::select('scheme_id', \App\Models\Scheme::getAll(), null, ['class' => 'form-control', 'placeholder' => 'Выберите ...']) !!}
    </div>

    <!-- Date Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('started', 'Начало действия:') !!}
        {!! Form::date('started', isset($route) ? $route->started : null, ['class' => 'form-control']) !!}
    </div>

    <!-- Date Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('finished', 'Окончание действия:') !!}
        {!! Form::date('finished', isset($route) ? $route->finished : null, ['class' => 'form-control']) !!}
    </div>

    <!-- Note Field -->
    <!--
    <div class="form-group col-sm-12">
        {!! Form::label('note', 'Условия перевозки багажа:') !!}
        {!! Form::textarea('note', null, ['class' => 'form-control']) !!}
    </div>
    -->

    <!-- Note Field -->
    <!--
    <div class="form-group col-sm-12">
        {!! Form::label('phones', 'Список контактных номеров телефона:') !!}
        {!! Form::textarea('phones', null, ['class' => 'form-control']) !!}
    </div>
    -->

    <!-- Status Field -->
    <div class="form-group col-sm-12">
        {!! Form::label('status', 'Статус:') !!}
        {!! Form::select('status', \App\Models\Route::statuses, null, ['class' => 'form-control']) !!}
    </div>

    <!-- Submit Field -->
    <div class="form-group col-sm-12">
        {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
        <a href="{!! route('routes.index') !!}" class="btn btn-default">Отменить</a>
    </div>

Example 3/resources/views/routes/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Маршруты</h1>
        <ol class="breadcrumb">
            <li><a href="{!! url('/search') !!}"><i class="fa fa-dashboard"></i>Главная</a></li>
            <li class="active">Маршруты</li>
        </ol>
    </section>
    <section class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>

        <div class="box box-primary">
            <div class="box-header">
                <h3 class="box-title pull-right">
                    <a class="btn btn-primary pull-right" href="{!! route('routes.create') !!}">Добавить</a>
                </h3>
            </div>
            <div class="box-body">
                @include('routes.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </section>
@endsection

Example 3/resources/views/routes/quotas.blade.php
<table class="table table-striped">
    <thead>
    <tr><th>Агент</th><th>Количество билетов</th><th colspan="1"></th></tr>
    </thead>
    <tbody>
    @foreach(\App\Models\Agent::where('id', '<>', \App\Models\Agent::GDAMALER_ID)->get() as $agent)
        <tr>
            {!! Form::open(['route' => 'routeQuotas.store']) !!}
                {!! Form::hidden('route_id', $route->id) !!}
                {!! Form::hidden('agent_id', $agent->id) !!}
                <td>
                    {!! $agent->name !!}
                </td>
                <td>
                    {!! Form::number('amount', $route->getAgentQuotaAmount($agent->id), ['class' => 'form-control', 'style' => 'width:150px']) !!}
                </td>
                <td>
                    <div class='btn-group'>
                        {!! Form::button('Сохранить', ['type' => 'submit', 'class' => 'btn btn-primary', 'style' => 'width:100px']) !!}
                    </div>
                </td>
            {!! Form::close() !!}
        </tr>
    @endforeach
    </tbody>
</table>

Example 3/resources/views/routes/route_prices.blade.php
    <table class="table table-responsive" id="routes-table">
        <thead>
            <tr><th colspan="4">Прейскурант маршрута</th></tr>
            <tr><th>Из</th><th>В</th><th>Цена</th><th colspan="3">Действия</th></tr>
        </thead>
        <tbody>
        @php ($route_end_point_id = 0)
        @php ($route_end_point_time = 0)
        @foreach($route->route_prices as $route_price)
        <tr>
            <td><b>{!! $route_price->from->city->name !!}</b><br>
                {!! $route_price->from->name !!}
            </td>
            <td>
                <b>{!! $route_price->to->city->name !!}</b><br>
                {!! $route_price->to->name !!}
            </td>
            <td>{!! $route_price->price !!} {!! $route_price->currency->short !!}</td>
            <td>
                {!! Form::open(['route' => ['routePrices.destroy', $route_price->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('routePrices.edit', [$route->id, 'route_price'=>$route_price->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Вы уверены?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
            @php ($route_end_point_id = 0)
            @php ($route_end_point_time = 0)
        @endforeach
        <tr>
            {!! Form::open(['route' => 'routePrices.store']) !!}
                {!! Form::hidden('route_id', $route->id) !!}
            <td>{!! Form::select('from_point_id', \App\Models\Point::getAllfromRoute($route->id), null, ['class' => 'form-control fine_select']) !!}</td>
            <td>{!! Form::select('to_point_id', \App\Models\Point::getAlltoRoute($route->id), null, ['class' => 'form-control fine_select']) !!}</td>
            <td style="white-space: nowrap;">
                        <!--<span class="input-group-addon">$</span>-->
                <div class="input-group" style="display: inline-block;">
                    {!! Form::text('price', null, ['class' => 'form-control', 'placeholder'=>'0.00', 'style'=>'width:50px;']) !!}
                </div>
               <div class="input-group" style="display: inline-block;">
                   {!! Form::select('currency_id', \App\Models\Currency::getAll(), null, ['class' => 'form-control', 'style'=>'width:71px;']) !!}
               </div>
            </td>
            <td>
                <div class='btn-group'>
                    {!! Form::submit('Добавить', ['class' => 'btn btn-primary']) !!}
                </div>
            </td>
            {!! Form::close() !!}
        </tr>
        </tbody>
    </table>

@section('scripts')
    <script>
        $(function () {
        });
    </script>
@endsection

Example 3/resources/views/routes/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>Маршрут</h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('routes.show_fields')
                    <a href="{!! route('routes.index') !!}" class="btn btn-default">Назад</a>
                </div>
            </div>
        </div>
    </div>
@endsection

Example 3/resources/views/routes/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $route->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $route->name !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $route->deleted_at !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $route->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $route->updated_at !!}</p>
</div>

Example 3/resources/views/routes/table.blade.php
<table class="table table-responsive" id="routes-table">
    <thead>
        <tr>
            <th>Название</th>
            <th>Маршрут</th>
            <th>Схема</th>
            <th>Начало</th>
            <th>Окончание</th>
            <th>Статус</th>
            <th colspan="3">Действия</th>
        </tr>
    </thead>
    <tbody>
    @foreach($routes as $route)
        <tr>
            <td>{!! $route->name !!}</td>
            <td>
                @foreach($route->route_points as $route_point)
                    {{ $route_point->from->city->name }}, {{ $route_point->from->name }} (<b>{{ date('H:i', mktime(0, 0, $route_point->getRealFromTimeInSeconds())) }}</b>)
                    <!-- - {{ $route_point->to->name }} ({{ date('H:i:s', mktime(0, 0, $route_point->to_time)) }}) --> <br/>
                @endforeach
            </td>
            <td>{!! $route->scheme->name !!}</td>
            <td>{!! isset($route->started)?$route->started->format('d-m-Y'):'-' !!}</td>
            <td>{!! isset($route->finished)?$route->finished->format('d-m-Y'):'-' !!}</td>
            <td>{!! \App\Models\Route::statuses[$route->status] !!}</td>
            <td>
                {!! Form::open(['route' => ['routes.destroy', $route->id], 'method' => 'delete']) !!}
                <div class='btn-group'>

                    <!--<a href="{!! route('routes.show', [$route->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>-->
                    <a href="{!! url('/trips/generate', ['route'=>$route->id]) !!}" class='btn btn-default btn-xs @if($route->status == 0) disabled @endif'><i class="glyphicon glyphicon-transfer" title="Создать рейсы"></i></a>
                    @if(isset($route->schedule))
                        <a href="{!! route('schedules.edit', [$route->schedule->id, 'route'=>$route->id]) !!}" class='btn btn-default btn-xs' title="Расписание маршрута"><i class="glyphicon glyphicon-tasks"></i></a>
                    @else
                        <a href="{!! route('schedules.create', ['route' => $route->id]) !!}" class='btn btn-default btn-xs' title="Добавить Расписание маршрута"><i class="glyphicon glyphicon-tasks"></i></a>
                    @endif
                    <a href="{!! url('/routes/clone', ['route'=>$route->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-copy" title="Копировать маршрут"></i></a>
                    <a href="{!! url('/routes/pricelist', ['route'=>$route->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-euro" title="Прейскурант"></i></a>
                    <a href="{!! route('routes.edit', [$route->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Вы уверены?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>