Example 3/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
  return redirect('home');
});

Route::get('/home', 'HomeController@index');

Auth::routes();

Route::get('/tickets/view/{viewer}', 'TicketController@view');

Route::middleware(['role:'.\App\Models\User::ROLE_SIMPLE_ID.','.\App\Models\User::ROLE_DISPATCHER_ID])->group(function () {
    Route::match(['GET', 'POST'], '/search', 'SearchController@index');
    Route::get('/tickets/checkclients', 'TicketController@checkclients');
    Route::get('/tickets/checkclient', 'TicketController@checkclient');
    Route::get('/tickets/checkplace', 'TicketController@checkPlace');
    Route::get('/tickets/cancel/{id}', 'TicketController@cancel');
    Route::resource('tickets', 'TicketController');
    Route::resource('trips', 'TripController');
    Route::get('/trips/tickets/{trip}', 'TripController@tickets');
    Route::get('/trips/waybill/{trip}', 'TripController@waybill');
    Route::get('/trips/generate/{route}', 'TripController@generate');
    Route::patch('/trips/blockedPlaces/{trip}', 'TripController@updateBlockedPlaces')
        ->name('trips.blockedPlaces.update');

    Route::get('/places/list', 'PlaceController@list');

    Route::get('/clients/list', 'ClientController@list');
    Route::get('/clients/clientsAutocomplite', 'ClientController@clientsAutocomplite');
    Route::resource('clients', 'ClientController');
});

Route::middleware(['role:'.\App\Models\User::ROLE_SIMPLE_ID])->group(function () {
    Route::get('/routes/clone/{route}', 'RouteController@clone');
    Route::get('/routes/pricelist/{route}', 'RouteController@pricelist');
    Route::resource('routes', 'RouteController');
    Route::resource('routeBlockedPlaces', 'RouteBlockedPlaceController');
    Route::resource('routePoints', 'RoutePointController');
    Route::get('points/restore/{id}', 'PointController@restore');
    Route::resource('points', 'PointController');
    Route::get('/routePrices/save', 'RoutePriceController@save');
    Route::get('/routePrices/saveCurrency', 'RoutePriceController@saveCurrency');
    Route::resource('routePrices', 'RoutePriceController');
    Route::resource('schedules', 'ScheduleController', [
        'parameters' => [
            'route' => 'route'
        ]
    ]);

    // Справочники
    Route::resource('agents', 'AgentController');
    Route::resource('langs', 'LangController');
    Route::resource('currencies', 'CurrencyController');
    Route::resource('ticketTypes', 'TicketTypeController', ['trip' => [
        'trip' => 'trip'
    ]]);
    Route::resource('drivers', 'DriverController');
    Route::resource('driverPhones', 'DriverPhoneController', ['parameters' => [
        'driverPhones' => 'driver'
    ]]);
    Route::resource('buses', 'BusController');
    Route::resource('countries', 'CountryController');
    Route::resource('cities', 'CityController');
    Route::resource('places', 'PlaceController');

    // Вспомогательные справочники (без UI)
    Route::resource('schemes', 'SchemeController');

    Route::get('/tripPointBlockeds/block/{trip}/{point}', 'TripPointBlockedController@block');
    Route::resource('tripPointBlockeds', 'TripPointBlockedController');

    Route::resource('dispatcherPhones', 'DispatcherPhoneController');

    Route::resource('settings', 'SettingsController');
    Route::get('/settings/general/{id}/edit', 'SettingsController@editGeneral')
        ->name('settings.general.edit');
    Route::patch('/settings/general/{id}/update', 'SettingsController@updateGeneral')
        ->name('settings.general.update');

    Route::resource('returns', 'ReturnsController');

    Route::resource('users', 'UserController');

    Route::resource('tradingPlatformPoints', 'TradingPlatformPointController', ['only' => [
        'store', 'destroy'
    ]]);
    Route::resource('tradingPlatformTicketVariants', 'TradingPlatformTicketVariantController', ['only' => [
        'store', 'update', 'destroy'
    ]]);
    Route::resource('tradingPlatformRoutes', 'TradingPlatformRoutesController', ['only' => [
        'store', 'destroy'
    ]]);
    Route::resource('tradingPlatforms', 'TradingPlatformController', ['only' => [
        'store', 'update', 'edit', 'destroy', 'create', 'index'
    ]]);
    Route::resource('agentTradingPlatforms', 'AgentTradingPlatformController');
    Route::resource('routeQuotas', 'RouteQuotaController', ['only' => [
        'store'
    ]]);
    Route::resource('tripQuotas', 'TripQuotaController', ['only' => [
        'store'
    ]]);
    Route::resource('activities', 'ActivityController', ['only' => [
        'index'
    ]]);
    Route::resource('reports', 'ReportController', ['only' => [
        'index'
    ]]);
});

Example 3/app/Models/TradingPlatformPoint.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class TradingPlatformPoint
 * @package App\Models
 * @version September 27, 2018, 5:53 pm UTC
 *
 * @property integer trading_platform_id
 * @property integer point_id
 * @property string name
 */
class TradingPlatformPoint extends Model
{
    use SoftDeletes;

    public $table = 'trading_platform_points';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
        'trading_platform_id',
        'point_id',
        'name'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'trading_platform_id' => 'integer',
        'point_id' => 'integer',
        'name' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'trading_platform_id' => 'required|numeric',
        'point_id' => 'required|numeric',
        'name' => 'required|string'
    ];

    public static $messages = [
        'name.required' => 'Необходимо указать название',
    ];

    public function tradingPlatform(){
        return $this->belongsTo('App\Models\TradingPlatform', 'trading_platform_id');
    }

    public function point(){
        return $this->belongsTo('App\Models\Point', 'point_id');
    }
}

Example 3/app/Http/Controllers/TradingPlatformPointController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateTradingPlatformPointRequest;
use App\Http\Requests\UpdateTradingPlatformPointRequest;
use App\Repositories\TradingPlatformPointRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class TradingPlatformPointController extends AppBaseController
{
    /** @var  TradingPlatformPointRepository */
    private $tradingPlatformPointRepository;

    public function __construct(TradingPlatformPointRepository $tradingPlatformPointRepo)
    {
        $this->tradingPlatformPointRepository = $tradingPlatformPointRepo;
    }

    /**
     * Display a listing of the TradingPlatformPoint.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->tradingPlatformPointRepository->pushCriteria(new RequestCriteria($request));
        $tradingPlatformPoints = $this->tradingPlatformPointRepository->all();

        return view('trading_platform_points.index')
            ->with('tradingPlatformPoints', $tradingPlatformPoints);
    }

    /**
     * Show the form for creating a new TradingPlatformPoint.
     *
     * @return Response
     */
    public function create()
    {
        return view('trading_platform_points.create');
    }

    /**
     * Store a newly created TradingPlatformPoint in storage.
     *
     * @param CreateTradingPlatformPointRequest $request
     *
     * @return Response
     */
    public function store(CreateTradingPlatformPointRequest $request)
    {
        $input = $request->all();

        $tradingPlatformPoint = $this->tradingPlatformPointRepository->create($input);

        Flash::success('Станция успешно сохранена.');

        return redirect(route('tradingPlatforms.edit', $input['trading_platform_id']));
    }

    /**
     * Display the specified TradingPlatformPoint.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $tradingPlatformPoint = $this->tradingPlatformPointRepository->findWithoutFail($id);

        if (empty($tradingPlatformPoint)) {
            Flash::error('Trading Platform Point not found');

            return redirect(route('tradingPlatformPoints.index'));
        }

        return view('trading_platform_points.show')->with('tradingPlatformPoint', $tradingPlatformPoint);
    }

    /**
     * Show the form for editing the specified TradingPlatformPoint.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $tradingPlatformPoint = $this->tradingPlatformPointRepository->findWithoutFail($id);

        if (empty($tradingPlatformPoint)) {
            Flash::error('Trading Platform Point not found');

            return redirect(route('tradingPlatformPoints.index'));
        }

        return view('trading_platform_points.edit')->with('tradingPlatformPoint', $tradingPlatformPoint);
    }

    /**
     * Update the specified TradingPlatformPoint in storage.
     *
     * @param  int              $id
     * @param UpdateTradingPlatformPointRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateTradingPlatformPointRequest $request)
    {
        $tradingPlatformPoint = $this->tradingPlatformPointRepository->findWithoutFail($id);

        if (empty($tradingPlatformPoint)) {
            Flash::error('Trading Platform Point not found');

            return redirect(route('tradingPlatformPoints.index'));
        }

        $tradingPlatformPoint = $this->tradingPlatformPointRepository->update($request->all(), $id);

        Flash::success('Trading Platform Point updated successfully.');

        return redirect(route('tradingPlatforms.edit', $request->input('trading_platform_id')));
    }

    /**
     * Remove the specified TradingPlatformPoint from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $tradingPlatformPoint = $this->tradingPlatformPointRepository->findWithoutFail($id);

        if (empty($tradingPlatformPoint)) {
            Flash::error('Trading Platform Point not found');

            return redirect(route('tradingPlatformPoints.index'));
        }

        $this->tradingPlatformPointRepository->delete($id);

        Flash::success('Станция успешно удалена.');

        return redirect(route('tradingPlatforms.edit', $tradingPlatformPoint->trading_platform_id));
    }
}

Example 3/resources/views/trading_platform_points/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Trading Platform Point
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'tradingPlatformPoints.store']) !!}

                        @include('trading_platform_points.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

Example 3/resources/views/trading_platform_points/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Trading Platform Point
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($tradingPlatformPoint, ['route' => ['tradingPlatformPoints.update', $tradingPlatformPoint->id], 'method' => 'patch']) !!}

                        @include('trading_platform_points.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

Example 3/resources/views/trading_platform_points/fields.blade.php
<!-- Trading Platform Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('trading_platform_id', 'Trading Platform Id:') !!}
    {!! Form::number('trading_platform_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Point Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('point_id', 'Point Id:') !!}
    {!! Form::number('point_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('tradingPlatformPoints.index') !!}" class="btn btn-default">Cancel</a>
</div>

Example 3/resources/views/trading_platform_points/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Trading Platform Points</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('tradingPlatformPoints.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('trading_platform_points.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

Example 3/resources/views/trading_platform_points/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Trading Platform Point
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('trading_platform_points.show_fields')
                    <a href="{!! route('tradingPlatformPoints.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

Example 3/resources/views/trading_platform_points/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $tradingPlatformPoint->id !!}</p>
</div>

<!-- Trading Platform Id Field -->
<div class="form-group">
    {!! Form::label('trading_platform_id', 'Trading Platform Id:') !!}
    <p>{!! $tradingPlatformPoint->trading_platform_id !!}</p>
</div>

<!-- Point Id Field -->
<div class="form-group">
    {!! Form::label('point_id', 'Point Id:') !!}
    <p>{!! $tradingPlatformPoint->point_id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $tradingPlatformPoint->name !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $tradingPlatformPoint->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $tradingPlatformPoint->updated_at !!}</p>
</div>

Example 3/resources/views/trading_platform_points/table.blade.php
<table class="table table-responsive" id="tradingPlatformPoints-table">
    <thead>
        <tr>
            <th>Trading Platform Id</th>
        <th>Point Id</th>
        <th>Name</th>
            <th colspan="3">Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach($tradingPlatformPoints as $tradingPlatformPoint)
        <tr>
            <td>{!! $tradingPlatformPoint->trading_platform_id !!}</td>
            <td>{!! $tradingPlatformPoint->point_id !!}</td>
            <td>{!! $tradingPlatformPoint->name !!}</td>
            <td>
                {!! Form::open(['route' => ['tradingPlatformPoints.destroy', $tradingPlatformPoint->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('tradingPlatformPoints.show', [$tradingPlatformPoint->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('tradingPlatformPoints.edit', [$tradingPlatformPoint->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>